name: Deploy TriaGen
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/TriaGen
            git pull origin main

            # 1. Setup Frontend Environment (Overwrite with fresh IP)
            echo "NEXT_PUBLIC_API_URL=http://40.192.105.1:4000" > apps/web/.env.local

            # 2. Setup Backend Environment (Securely injecting Secrets)
            echo "PORT=4000" > apps/api/.env
            echo "HOST=0.0.0.0" >> apps/api/.env
            echo "NODE_ENV=production" >> apps/api/.env
            echo "FRONTEND_URL=http://40.192.105.1:3000" >> apps/api/.env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> apps/api/.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> apps/api/.env
            echo "AWS_REGION=ap-south-2" >> apps/api/.env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> apps/api/.env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> apps/api/.env
            echo "AWS_BUCKET_NAME=triagen-uploads-ramana" >> apps/api/.env
            echo "REDIS_HOST=redis" >> apps/api/.env
            echo "REDIS_PORT=6379" >> apps/api/.env

            # 3. Clean and Restart Containers
            docker-compose down
            docker system prune -f
            docker-compose up -d --build
